list.of.exturnal.properties=server.port,spring.rabbitmq.host,spring.rabbitmq.port,spring.rabbitmq.username,spring.rabbitmq.password,spring.rabbitmq.exchange,spring.rabbitmq.routingkey.getter,spring.rabbitmq.routingkey.setter,spring.rabbitmq.queue.to.bzionservice,spring.rabbitmq.queue.from.bzionservice

spring.application.name=bz-ion-service
server.port=8081
#spring.rabbitmq.host=localhost

#rabbit
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=bz-ion-service
spring.rabbitmq.password=123qwerty
spring.rabbitmq.exchange=amq.direct
spring.rabbitmq.routingkey.getter=amq.direct.1
spring.rabbitmq.routingkey.setter=amq.direct.2


#rabbit-queues
spring.rabbitmq.queue.to.bzionservice=bz-ion-service-queue
spring.rabbitmq.queue.from.bzionservice=bz-ion-service-response
