spring.application.name=bz-ion-service
server.port=8081
#spring.rabbitmq.host=localhost

#rabbit
spring.rabbitmq.port=5673
spring.rabbitmq.username=bz-ion-service
spring.rabbitmq.password=123qwerty
spring.rabbitmq.queue=bz-ion-service-queue
spring.rabbitmq.exchange=amq.direct
spring.rabbitmq.host=u1
spring.rabbitmq.routingkey=/