list.of.exturnal.properties=server.port,spring.rabbitmq.host,spring.rabbitmq.port,spring.rabbitmq.username,spring.rabbitmq.password,spring.rabbitmq.exchange,spring.rabbitmq.routingkey.getter,spring.rabbitmq.routingkey.setter,spring.rabbitmq.queue.to.bzionservice,spring.rabbitmq.queue.from.bzionservice

spring.application.name=bz-ion-service
#server.port=8081
server.port=8082
#spring.rabbitmq.host=localhost

#rabbit
spring.rabbitmq.host=u1
spring.rabbitmq.port=5672
spring.rabbitmq.username=bz-ion-service
spring.rabbitmq.password=123qwerty
spring.rabbitmq.exchange=measured-remainders.direct

spring.rabbitmp.transfer.exchange=warehouse-transfer.direct

#key
inventory_measured-remainders.key=inventory.measured-remainders
update_measured-remainder.key=update.measured-remainder
response_measured-remainder.key=response.measured-remainder
transfer_transfer_by_locations.key=develop.transfer.by.bins


#rabbit-queues
inventory_measured-remainders=inventory.measured-remainders
update_measured-remainder=update.measured-remainder
update_response_measured-remainder=update.response.measured-remainder
transfer_transfer_by_locations=develop.transfer.by.bins
#container
PlacementContainerMessageListener=develop.placement.container

#queue.key.map.request={\
#  'inventory_measured-remainders.queue':'',\
#  'inventory_measured-remainders.key':'',\
#  }

queue.key.map.return={\
  'inventoryManagement.queue':'response.to.inventory.measured-remainders',\
  'inventoryManagement.key':'response.to.inventory.measured-remainders',\
  'inventoryManagement.exchange':'measured-remainders.direct',\
  'writeOffOfGoods.queue':'response.to.update.measured-remainder',\
  'writeOffOfGoods.key':'response.to.update.measured-remainder',\
  'writeOffOfGoods.exchange':'measured-remainders.direct',\
  'TransferItemByBinTransactionMessage.queue':'develop.response.to.transfer.by.bins',\
  'TransferItemByBinTransactionMessage.key':'develop.response.to.transfer.by.bins',\
  'TransferItemByBinTransactionMessage.exchange':'develop.warehouse-transfer.direct',\
  'PlacementContainerMessage.queue':'develop.response.to.placement.container',\
  'PlacementContainerMessage.key':'develop.response.to.placement.container',\
  'PlacementContainerMessage.exchange':'develop.container.direct'\
  }