<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://spring.io/guides/gs-producing-web-service"
           xmlns:tns="http://spring.io/guides/gs-producing-web-service" elementFormDefault="qualified">

    <xs:element name="GetHandlingUnitsRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="handlingUnitsReq" type="xs:string" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetHandlingUnitsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="handlingUnitsResp" type="tns:Unit4TransferResp" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Unit4TransferResp">
        <xs:sequence>
            <xs:element name="mvid" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="datentime" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="actioncode" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="user" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="handlingUnit" type="tns:handlingUnit" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="handlingUnit">
        <xs:sequence>
            <xs:element name="huid" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfHght" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfWdth" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cwar" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfLoca" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfLose" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="status" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="comment" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="SetAcknowledgeRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mvid" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="success" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="datentime" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="tenantId" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="actionCodeField" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="errorlog" type="tns:ResultList" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ResultList">
        <xs:sequence>
            <xs:element name="error" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="SetAcknowledgeResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="noted" type="xs:string" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>