<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://spring.io/guides/gs-producing-web-service"
           xmlns:tns="http://spring.io/guides/gs-producing-web-service" elementFormDefault="qualified">

    <xs:element name="GetHandlingUnitsRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fromIon" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetHandlingUnitsResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="handlingUnitsResp" type="tns:unit4TransferResp" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="unit4TransferResp">
        <xs:sequence>
            <xs:element name="mvid" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="datentime" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="actioncode" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="handlingUnit" type="tns:handlingUnit" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="handlingUnit">
        <xs:sequence>
            <xs:element name="huid" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfHght" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfWdth" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cwar" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfLoca" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="cdfLose" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="SetAcknowledgeRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mvid" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="success" type="xs:string" maxOccurs="1" minOccurs="1"/>
                <xs:element name="errorlog" type="tns:resultList" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="resultList">
        <xs:list itemType="xs:string">
        </xs:list>
    </xs:simpleType>

    <xs:element name="SetAcknowledgeResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="noted" type="xs:string" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>